# ============================================================
# Beam-generator validation test
# 100 events at 1, 2, and 4 GeV
# ============================================================

/det/setAbsorberMaterial G4_Fe
/det/setAbsorberThickness 35.14 mm

/run/initialize

/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/gun/particle e-

/gun/setNominalEnergy 1 GeV
/run/beamOn 100

/gun/setNominalEnergy 2 GeV
/run/beamOn 100

/gun/setNominalEnergy 4 GeV
/run/beamOn 100
